# Generated by Django 2.0.3 on 2018-04-02 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='sumary',
            new_name='summary',
        ),
    ]
